apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: server
          image: gcr.io/useful-cathode-334010/shipping:null.2
          ports:
            - containerPort: 50051
          envFrom:
          - configMapRef:
              name: lightstep-configmap
          env:
            - name: OTEL_EXPORTER_OTLP_SPAN_ENDPOINT
              value: otel-collector:55680
            - name: OTEL_EXPORTER_OTLP_SPAN_INSECURE
              value: 'true'
            - name: PORT
              value: "50051"
            - name: LS_SERVICE_NAME
              value: shippingservice
            - name: LS_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lightstep-credentials
                  key: accessToken
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
